### ISSUE TITLE
如何set `share=True`

### ISSUE THREAD

**Issue by zhuxiaosheng** [OpenBMB/AgentVerse#27]
很好的项目，非常期待尝试成功，遇到两个问题：
1.如何set `share=True`
2.export OPENAI_API_KEY ，仍然warning ，提示要设置OPENAI_API_KEY

我是在colab上运行的，![截屏2023-08-13 11 05 26](https://github.com/OpenBMB/AgentVerse/assets/2718879/ea22c28f-2a02-4a34-a514-7b00e7c9ae6e)

**Comment by chenweize1998** [comment]
1. You can add `share=True` at https://github.com/OpenBMB/AgentVerse/blob/06e97ef69de4c136a9140223903982442b13084f/main_demo.py#L16
2. Personally, I don't use Colab, so I cannot be 100% sure about what the problem is. However, I googled it and found that setting environment variables in Colab seems to be tricky. You can try exporting your OpenAI key by adding the following code at the top of  `main_demo.py`
```python
import os
os.environ["OPENAI_API_KEY"] = "sk-xxx"
```
Also, remember to reset your API key, as it might be leaked through your screen capture.

**Comment by zhuxiaosheng** [comment]
谢谢您的回复，还是没能明白怎么添加share=True 
是作为参数吗 ，这样 ui.launch(share=True) ？ 貌似还是不行

**Comment by chenweize1998** [comment]
Ah sorry about that. You may need to add the argument at https://github.com/OpenBMB/AgentVerse/blob/06e97ef69de4c136a9140223903982442b13084f/agentverse/demo.py#L486C62-L486C62

**Comment by zhuxiaosheng** [comment]
奇怪，486行直接传参貌似不能生成gradio link。 我直接修改了lanuch：share: bool = True, 可以正常启动
